added potentially broken drivers for aix, hpux, irix, and solaris, as well as configure-able detection of which driver to use, courtesy of Isaac Richards

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -782,6 +782,33 @@ fi
 
 
 
+
+# Make sure we can run config.sub.
+if $ac_config_sub sun4 >/dev/null 2>&1; then :
+else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
+fi
+
+echo $ac_n "checking host system type""... $ac_c" 1>&6
+echo "configure:793: checking host system type" >&5
+
+host_alias=$host
+case "$host_alias" in
+NONE)
+  case $nonopt in
+  NONE)
+    if host_alias=`$ac_config_guess`; then :
+    else { echo "configure: error: can not guess host type; you must specify one" 1>&2; exit 1; }
+    fi ;;
+  *) host_alias=$nonopt ;;
+  esac ;;
+esac
+
+host=`$ac_config_sub $host_alias`
+host_cpu=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+host_vendor=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+host_os=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+echo "$ac_t""$host" 1>&6
+
 # Check whether --enable-shared or --disable-shared was given.
 if test "${enable_shared+set}" = set; then
   enableval="$enable_shared"
@@ -827,33 +854,6 @@ esac
 else
   enable_static=yes
 fi
-
-
-# Make sure we can run config.sub.
-if $ac_config_sub sun4 >/dev/null 2>&1; then :
-else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
-fi
-
-echo $ac_n "checking host system type""... $ac_c" 1>&6
-echo "configure:839: checking host system type" >&5
-
-host_alias=$host
-case "$host_alias" in
-NONE)
-  case $nonopt in
-  NONE)
-    if host_alias=`$ac_config_guess`; then :
-    else { echo "configure: error: can not guess host type; you must specify one" 1>&2; exit 1; }
-    fi ;;
-  *) host_alias=$nonopt ;;
-  esac ;;
-esac
-
-host=`$ac_config_sub $host_alias`
-host_cpu=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
-host_vendor=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
-host_os=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
-echo "$ac_t""$host" 1>&6
 
 # Extract the first word of "ranlib", so it can be a program name with args.
 set dummy ranlib; ac_word=$2
@@ -1563,7 +1563,7 @@ else
 fi
 echo "$ac_t""$CPP" 1>&6
 
-for ac_hdr in sys/soundcard.h
+for ac_hdr in sys/soundcard.h machine/soundcard.hi sys/audio.h sys/audioio.h sys/audio.io.h sun/audioio.hi dmedia/audio.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
@@ -1604,8 +1604,54 @@ fi
 done
 
 
+if test "${ac_cv_header_sys_soundcard_h}" = "yes" || \
+   test "${ac_cv_header_machine_soundcard_h}" = "yes"; then
+   cat >> confdefs.h <<\EOF
+#define DRIVER_OSS 1
+EOF
+
+fi
+
+if test "${ac_cv_header_sys_audio_h}" = "yes"; then
+   case ${host_os} in
+   hpux*)
+       cat >> confdefs.h <<\EOF
+#define DRIVER_HPUX 1
+EOF
+
+   ;;
+   aix*)
+       cat >> confdefs.h <<\EOF
+#define DRIVER_AIX 1
+EOF
+
+   esac
+fi
+
+if test "${ac_cv_header_sys_audioio_h}" = "yes" || \
+   test "${ac_cv_header_sys_audio_io_h}" = "yes" || \
+   test "${ac_cv_header_sun_audioio_h}" = "yes"; then
+   case ${host_os} in
+   solaris*)
+      cat >> confdefs.h <<\EOF
+#define DRIVER_SOLARIS 1
+EOF
+
+   esac
+fi
+
+if test "${ac_cv_header_dmedia_audio_h}" = "yes"; then
+   case ${host_os} in
+   irix*)
+      cat >> confdefs.h <<\EOF
+#define DRIVER_IRIX 1
+EOF
+
+   esac
+fi
+
 echo $ac_n "checking whether ${MAKE-make} sets \${MAKE}""... $ac_c" 1>&6
-echo "configure:1609: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "configure:1655: checking whether ${MAKE-make} sets \${MAKE}" >&5
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_prog_make_${ac_make}_set'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
